server:
    port: 9101
    servlet:
        context-path: /vehicle_js

mybatis-plus:
    mapper-locations: classpath:mapper/*/*.xml


# OMS调用接口鉴权
tmsSecret: "PS2lElAqBMwKY9ZTjk8wOLBAtXSLvXDGfs1WrGpheQe"
tmsKet: "QaSgC3K1a5KMF8XQm8Y0CmFenTvzs04iWx9uzSTcgkt"

pagehelper:
    helperDialect: oracle
    supportMethodsArguments: true
    params: count=countSql
servicePath: "http://127.0.0.1:9095/services"

# 通知相关
sourceFrom: 'A0002'
token: '20F50330B550BD9922892725C9305CC5'
inFromUrl: 'http://47.112.108.213:7003/api/Notice/SendNotice'

spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    devtools:
        restart:
            enabled:true
    datasource:
        dynamic:
            datasource:
                master :
                     #公司内部测试数据库
                    driver-class-name: oracle.jdbc.driver.OracleDriver
                    url: jdbc:oracle:thin:@192.168.3.149:1521:ORCL
                    username: NJ_CMSCL_SETTLEMENT_TEST
                    password: NJ_CMSCL_SETTLEMENT_TEST_1QA
                    druid:
                        initial-size: 6
                vl_oracle :
                    driver-class-name: oracle.jdbc.driver.OracleDriver
                    url: jdbc:oracle:thin:@218.94.154.158:1521:VL
                    username: vl
                    password: cmscl@vl
                    druid:
                        initial-size: 5